import { History } from "history";
import { useState, useContext } from "react";
import { startLoading, stopLoading } from "./loading";
import { Actions as LoadingActions } from "../reducers/loading";
import axios from "axios";
import {
  CREATE_RECOMMENDATION,
  CREATE_RECOMMENDATION_ERROR,
  CLEAR_CREATE_RECOMMENDATION_ERROR,
} from "./Types";
import { Actions } from "../reducers/createCategory";
import { API_URL } from "./serverConnection";
import ModelOutputContext from "../contexts/ModelOutputContext";
import getUser from "../helpers/DecodeJwt";
import storeRatings from "./storeRatings";
export const createRecommendations =
  (categoryMap) => async (dispatch, loadingDispatch) => {
    try {
      const {
        user_id,
        twod_animation,
        threed_animation,
        character_animation,
        threed_modelling,
        concept_art,
        digital_painting,
        drawing,
        illustration,
        rendering,
        comic_book_illustration,
        brand_design,
        product_design,
        creativity,
        digital_publishing,
        fashion_design,
        logo_design,
        banner_design,
        poster_design,
        typography,
        visual_effects,
        threed,
        composing,
        keying,
        motion_graphics,
        oil_painting,
        acrylic_painting,
        procreate_art,
        sketching,
        pencil_art,
        photography,
        digital_photography,
        photography_mobile,
        potrait_photography,
        macro_photography,
        commercial_photography,
        architectural_photography,
        landscape_photography,
        photoshop,
        blender,
        level_design,
        unreal_engine,
        unity,
        digital_game_art,
        pixel_art,
        game_development,
        premier_pro,
        illustrator,
        after_effects,
        autocad,
        sketch,
        lightroom,
        autodesk,
        procreate,
        maya,
        film_making,
        cinematography,
        video_editing,
        mobile_video_editing,
        video_film_production,
        video_audio,
        video_gears,
      } = categoryMap;
      console.log("comic_book_illustration", comic_book_illustration);
      startLoading(loadingDispatch);
      const result = await axios.post(`${API_URL}/user/user-recommendations`, {
        user_id,
        twod_animation,
        threed_animation,
        character_animation,
        threed_modelling,
        concept_art,
        digital_painting,
        drawing,
        illustration,
        rendering,
        comic_book_illustration,
        brand_design,
        product_design,
        creativity,
        digital_publishing,
        fashion_design,
        logo_design,
        banner_design,
        poster_design,
        typography,
        visual_effects,
        threed,
        composing,
        keying,
        motion_graphics,
        oil_painting,
        acrylic_painting,
        procreate_art,
        sketching,
        pencil_art,
        photography,
        digital_photography,
        photography_mobile,
        potrait_photography,
        macro_photography,
        commercial_photography,
        architectural_photography,
        landscape_photography,
        photoshop,
        blender,
        level_design,
        unreal_engine,
        unity,
        digital_game_art,
        pixel_art,
        game_development,
        premier_pro,
        illustrator,
        after_effects,
        autocad,
        sketch,
        lightroom,
        autodesk,
        procreate,
        maya,
        film_making,
        cinematography,
        video_editing,
        mobile_video_editing,
        video_film_production,
        video_audio,
        video_gears,
      });
      console.log("result", result);
      // console.log("data to actions in createRecommendations in actions", {
      //   user_id,
      //   twod_animation,
      //   threed_animation,
      //   character_animation,
      //   threed_modelling,
      //   concept_art,
      //   digital_painting,
      //   drawing,
      //   illustration,
      //   rendering,
      //   comic_book_illustration,
      //   brand_design,
      //   product_design,
      //   creativity,
      //   digital_publishing,
      //   fashion_design,
      //   logo_design,
      //   banner_design,
      //   poster_design,
      //   typography,
      //   visual_effects,
      //   threed,
      //   composing,
      //   keying,
      //   motion_graphics,
      //   oil_painting,
      //   acrylic_painting,
      //   procreate_art,
      //   sketching,
      //   pencil_art,
      //   photography,
      //   digital_photography,
      //   photography_mobile,
      //   potrait_photography,
      //   macro_photography,
      //   commercial_photography,
      //   architectural_photography,
      //   landscape_photography,
      //   photoshop,
      //   blender,
      //   level_design,
      //   unreal_engine,
      //   unity,
      //   digital_game_art,
      //   pixel_art,
      //   game_development,
      //   premier_pro,
      //   illustrator,
      //   after_effects,
      //   autocad,
      //   sketch,
      //   lightroom,
      //   autodesk,
      //   procreate,
      //   maya,
      //   film_making,
      //   cinematography,
      //   video_editing,
      //   mobile_video_editing,
      //   video_film_production,
      //   video_audio,
      //   video_gears,
      // });
      stopLoading(loadingDispatch);
      dispatch({
        type: CREATE_RECOMMENDATION,
        payload: result,
      });
      clearErrors(dispatch);
    } catch (err) {
      stopLoading(loadingDispatch);
      dispatch({
        type: CREATE_RECOMMENDATION_ERROR,
        payload: err.response.data.message,
      });
    }
  };

export const clearErrors = (dispatch) => {
  dispatch({
    type: CLEAR_CREATE_RECOMMENDATION_ERROR,
  });
};
