//All action types are mentioned here as constants
export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY";
export const CLEAR_CREATE_CATEGORY_ERROR = "CREATE_CATEGORY";

export const CREATE_RECOMMENDATION = "CREATE_RECOMMENDATION";
export const CREATE_RECOMMENDATION_ERROR = "CREATE_RECOMMENDATION_ERROR";
export const CLEAR_CREATE_RECOMMENDATION_ERROR =
  "CLEAR_CREATE_RECOMMENDATION_ERROR";

export const CREATE_RATING = "CREATE_RATING";
export const CREATE_RATING_ERROR = "CREATE_RATING_ERROR";
export const CLEAR_CREATE_RATING_ERROR = "CLEAR_CREATE_RATING_ERROR";

export const MODEL_OUTPUT = "MODEL_OUTPUT";
export const MODEL_OUTPUT_ERROR = "MODEL_OUTPUT_ERROR";
export const CLEAR_MODEL_OUTPUT_ERROR = "CLEAR_MODEL_OUTPUT_ERROR";

export const MODEL_OUTPUT_2 = "MODEL_OUTPUT_2";
export const MODEL_OUTPUT_2_ERROR = "MODEL_OUTPUT_2_ERROR";
export const CLEAR_MODEL_OUTPUT_2_ERROR = "CLEAR_MODEL_OUTPUT_2_ERROR";
