// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXt95enXfu1M_LWz1ZrdA6YRNdqKU_LXE',
    appId: '1:591328014889:web:18b8f932b0036d548b2238',
    messagingSenderId: '591328014889',
    projectId: 'pro1-da010',
    authDomain: 'pro1-da010.firebaseapp.com',
    storageBucket: 'pro1-da010.appspot.com',
    measurementId: 'G-DYYJQ0VVMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC0U2p59F2fuVhI_2cqpmjLbjWukXomjk',
    appId: '1:591328014889:android:58a0421e597fc2538b2238',
    messagingSenderId: '591328014889',
    projectId: 'pro1-da010',
    storageBucket: 'pro1-da010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKPAnWnVrC0yuZR6NUgeEAsSIjozH4CJE',
    appId: '1:591328014889:ios:0780583113a1e4de8b2238',
    messagingSenderId: '591328014889',
    projectId: 'pro1-da010',
    storageBucket: 'pro1-da010.appspot.com',
    androidClientId:
        '591328014889-hsiucj5rm44n9l45eh7arhij3vu7ur5q.apps.googleusercontent.com',
    iosClientId:
        '591328014889-jcgdd60b1i1sfls7s464bm8dk67mfn3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.pro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKPAnWnVrC0yuZR6NUgeEAsSIjozH4CJE',
    appId: '1:591328014889:ios:0780583113a1e4de8b2238',
    messagingSenderId: '591328014889',
    projectId: 'pro1-da010',
    storageBucket: 'pro1-da010.appspot.com',
    androidClientId:
        '591328014889-hsiucj5rm44n9l45eh7arhij3vu7ur5q.apps.googleusercontent.com',
    iosClientId:
        '591328014889-jcgdd60b1i1sfls7s464bm8dk67mfn3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.pro',
  );
}
